spring.application.name=TrashMaster
spring.datasource.url=jdbc:postgresql://localhost:5432/TrashMaster
spring.datasource.username=postgres
spring.datasource.password=Jindal@04
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true